### ISSUE TITLE
Free variables sometimes appear in reduced terms

### ISSUE THREAD

**Issue by kuruczgy** [idris-lang/Idris2#2461] opened 2022-05-06 19:55 UTC
# Steps to Reproduce
Evaluate in the REPL:
```idris
\x => (\y => the Bool $ if y then y else y) x
```

# Expected Behavior
```idris
\x => if x then x else x
```

# Observed Behavior
```idris
\x => if x then y else y
```
Note how `y` appears free in this reduced term.

Am I just missing something here? Is it somehow implicitly bound? How can I show it? (I also tried turning `showtypes` and `showimplicits` on.)

**Comment by gallais** [comment] 2022-05-06 19:59
This is a duplicate of #1282

**Closed by gallais** 2022-05-06 19:59 UTC
