### ISSUE TITLE
0.6.0 `mismatch between x and x`, variable capture

### ISSUE THREAD

**Issue by jasonhemann** [idris-lang/Idris2#2958] opened 2023-04-29 19:10 UTC
In 0.6.0, loading the below file yields the error message below. The `mismatch between x and x` message was the part I wanted to bring to attention. I understand there's an accidental capture in the first lambda expression, but that doesn't seem like the most enlightening way to express it. 

```
module Bug
import Data.Vect

abc : (v : Vect w Nat) -> (x : Nat)  -> (y : Nat) -> (foldrImpl (*) 1 (\x => x * (y * x)) v) = 1

baz : {v : Vect w Nat} -> {x : Nat} -> {y : Nat}  -> (foldrImpl (*) 1 (\w => w) (x :: (y :: v))) = 1
baz = abc v x y
```
```
- + Errors (1)
 `-- Bug.idr line 7 col 6:
     While processing right hand side of baz. When unifying:
         foldrImpl (*) 1 (\x => x * (y * x)) v
     and:
         foldrImpl (*) 1 (((\w => w) . ((x *))) . ((y *))) v
     Mismatch between: x and x.
     
     Bug:7:7--7:16
      3 | 
      4 | abc : (v : Vect w Nat) -> (x : Nat)  -> (y : Nat) -> (foldrImpl (*) 1 (\x => x * (y * x)) v) = 1
      5 | 
      6 | baz : {v : Vect w Nat} -> {x : Nat} -> {y : Nat}  -> (foldrImpl (*) 1 (\w => w) (x :: (y :: v))) = 1
      7 | baz = abc v x y
                ^^^^^^^^^
```    
Additionally, if you replace the RHS of baz with a hole, the unsolved hole expression does that same inadvertent capture.

```
module Bug
import Data.Vect

baz : {v : Vect w Nat} -> {x : Nat} -> {y : Nat}  -> (foldr (*) 1 (x :: (y :: v))) = 1
baz = ?efg
```
```
Holes

This buffer displays the unsolved holes from the currently-loaded code. Press
the [P] buttons to solve the holes interactively in the prover.

- + "Bug.efg" [P]
 `--       0  w : Nat
              v : Vect w Nat
              x : Nat
              y : Nat
     ----------------------------------------------------------------------------------------
      "Bug.efg" : foldrImpl (\arg => \arg => mult arg arg) 1 (\x => mult x (mult y x)) v = 1
```

**Comment by gallais** [comment] 2023-04-30 08:05
> Mismatch between: x and x.

tells you there is no capture, but that the error printing is less than ideal.
I'll call this a duplicate of #35.

**Closed by gallais** 2023-04-30 08:05 UTC
