### ISSUE TITLE
Network not working as it should.

### ISSUE THREAD

**Issue by felipegchi** [idris-lang/Idris2#2211] opened 2021-12-21 22:51 UTC
I'm trying to receive the binary data `'\x10\x00\xef\xbf\x09\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74\x1f\xef\x02'` (that corresponds to [packet_size (16), id (0), host, port]) from a TCP server and put it inside a Buffer but i'm getting some strange behaviour from `recv` and `setString` due to a zeroed byte. 

# Steps to Reproduce
1. Run https://gist.github.com/felipegchi/ef50e5c8bc3fb474396344dd79cc390c with chez backend.
2. Run in terminal: `printf '\x10\x00\xef\xbf\x09\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74\x1f\xef\x02' | nc localhost PORT`
3. change the 2 in the line `readSome 2 client` to a big number.

# Expected Behavior
When n=100 in `readSome`: ```Str: "\DLE\NUL\65533\STX\tlocalhost\US\65533\STX", Len: 17, Buf: [16, 0, 239, 191, 9, 108, 111, 99, 97, 108, 104, 111, 115, 116, 31, 239, 2]```

When n=2 in `readSome`: 
```
Str: "\DLE", Len: 2, Buf: [16, 0]
Str: "\65533", Len: 2, Buf: [239, 191]
Str: "\tl", Len: 2, Buf: [9, 108]
Str: "oc", Len: 2, Buf: [111, 99]
Str: "al", Len: 2, Buf: [97, 108]
Str: "ho", Len: 2, Buf: [104, 111]
Str: "st", Len: 2, Buf: [115, 116]
Str: "\US\65533", Len: 2, Buf: [31, 239]
Str: "\STX", Len: 1, Buf: [2]
```

# Observed Behavior
When n=100 in `readSome`: ```Str: "\DLE", Len: 17, Buf: [16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]```

When n=2 in `readSome`: 
```
Str: "\DLE", Len: 2, Buf: [16, 0]
Str: "\65533", Len: 2, Buf: [239, 191]
Str: "\tl", Len: 2, Buf: [9, 108]
Str: "oc", Len: 2, Buf: [111, 99]
Str: "al", Len: 2, Buf: [97, 108]
Str: "ho", Len: 2, Buf: [104, 111]
Str: "st", Len: 2, Buf: [115, 116]
Str: "\US\65533", Len: 2, Buf: [31, 239]
Str: "\STX", Len: 1, Buf: [2]
```

**Comment by melted** [comment] 2021-12-22 00:02
It's passed as a string to and from C, and strings are null-terminated on the C side of the chez FFI. There is a network interface using buffers in Raw.idr. The problem is that I strongly suspect that it's broken and it has gone unnoticed because no one has used it. The reason I assume that is that it does conversion to and from network byte order in the _buf functions and that is not something that should be done with the payload. You can try to remove that stuff and see if that will work.

Now that I think of it, I actually have a dusty old commit using Data.Buffer instead of string, and that provides a string interface too using conversion. Let's see if I can dig it up and see if I can rebase it.

**Comment by octeep** [comment] 2022-02-16 22:09
Now that #2308 has been merged, `recvBytes` can be used instead to directly receive binary data instead of using string.

**Closed** 2022-02-17 13:29 UTC
