### ISSUE TITLE
Mismatch between: n and n (implicitly bound at ...)

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris2#792] opened 2020-11-25 09:52 UTC
# Steps to Reproduce

Download and type check https://github.com/nicolabotta/Idris2-issues/blob/master/Mismatch.lidr

# Expected Behavior

The file type checks fine.

# Observed Behavior

```
nicola@lt561:~/github/nicolabotta/Idris2-issues$ idris2 Mismatch.lidr
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.2.1-22bfa9097
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/      Type :? for help                     

Welcome to Idris 2.  Enjoy yourself!
1/1: Building Mismatch (Mismatch.lidr)
Error: While processing right hand side of biLemma. While processing right hand side of biLemma,ops. When
unifying (ps' : PolicySeq (S t) n) ->
(x : X (S t)) -> val ps' x <= val (bi (S t) n) x and (ps' : PolicySeq t n) ->
(x : X t) -> val ps' x <= val ps x.
Mismatch between: n and n (implicitly bound at Mismatch.lidr:91:10--91:33).

Mismatch.lidr:91:18--91:33
    |
 91 | >          ops  =  biLemma (S t) n
    |                  ^^^^^^^^^^^^^^^

Mismatch>
```

# Remarks

The file type checks fine in Idris 1. I would expect it to type check fine in Idris 2 as well. The error message seems to suggest that the Idris 2 type checker fails to recognize that `ps   =  bi (S t) n` as stated at line 89.

**Comment by gallais** [comment] 2020-11-25 17:54
As the error message suggests, the problem is that the `n` is implicitly bound
on line 91 and that is not equal to the other one (bound on line 87). This is
because Idris 2 will implicitly generalise over any lowercase unapplied variable
showing up in a type.

In Idris 1, only the out-of-scope variables would be generalised but the criterion
was changed for a simpler one that is stable under e.g. dependencies exporting
new names.

One possible fix is to give `ps` & others a name starting with an uppercase letter:

```idris
>   where  Ps   :  PolicySeq (S t) n
>          Ps   =  bi (S t) n
>          ops  :  OptPolicySeq Ps
>          ops  =  biLemma (S t) n
>          P    :  Policy t
>          P    =  optExt Ps
>          oep  :  OptExt Ps P
>          oep  =  optExtSpec Ps
```

Related: #621

**Comment by nicolabotta** [comment] 2020-11-26 07:00
@gallais Thanks for looking into this! I have to admit, that I do not understand your explanation: if Idris 2 implicitly generalises over any lowercase unapplied variable, why does your fix work? At line 87:

```
> biLemma t (S n)  =  Bellman Ps ops P oep 
```

Idris 2 should then implicitly generalize over `ops` and `oep` and fail to type check. Instead, it happily takes `ops` and `oep` to be equal to `biLemma (S t) n` and `optExtSpec Ps` as stated in the `where` clause!

**Comment by gallais** [comment] 2020-11-26 09:28
> Idris 2 will implicitly generalise over any lowercase unapplied variable **showing up in a type**

**Comment by nicolabotta** [comment] 2020-11-26 14:28
@gallais Thanks for the clarification! What about `n` in

```
>   where  Ps   :  PolicySeq (S t) n
```

It is an unapplied variable that shows up in a type and yet Idris 2 does **not** generalize over `n`. 

I am mildly confused and, to me, the new rule seems like a regression with respect to Idris 1. Is there a way of tackling the problem without having to uppercase the initials of unapplied variable that shows up in types?

Uppercasing is not really a viable option for me: it leads to programs that are hard to read and understand, especially in the context of literate programming.

**Comment by gallais** [comment] 2020-11-26 14:46
> What about n in
>  ```idris
> >   where  Ps   :  PolicySeq (S t) n
> ```

Hmm. I don't remember how this is handled.

>  Is there a way of tackling the problem without having to uppercase the initials
> of unapplied variable that shows up in types?

This works for instance:

```idris
> biLemma  :  Functor M => (t : Nat) -> (n : Nat) -> OptPolicySeq (bi t n)
> biLemma t  Z     =  nilOptPolicySeq
> biLemma t (S n)  =  Bellman ps ops p oep
>   where  ps   :  PolicySeq (S t) n
>          ps   =  bi (S t) n
>          ops  :  OptPolicySeq {n} {t = S t} ?
>          ops  =  biLemma (S t) n
>          p    :  Policy t
>          p    =  optExt ps
>          oep  :  OptExt {n} {t} ? ?
>          oep  =  optExtSpec ps
```

You can also turn auto implicits off like so: `%unbound_implicits off`.

**Comment by nicolabotta** [comment] 2020-11-26 15:26
> Hmm. I don't remember how this is handled.

Well ... if this is not fully clear to you ... how shall it be clear to the common Idris user! This suggests that the new rule is perhaps not adequate. I am not an expert but my take is that if a name is in scope, this is not by chance and there is no point in generalizing on it.

> You can also turn auto implicits off like so: `%unbound_implicits off`.

Thanks, that is what I was looking for! The whole IdrisLibs (https://gitlab.pik-potsdam.de/botta/IdrisLibs) was developed in Idris 1 with `%auto_implicits off` (and `%default total` and `%access public export`). 

I am now trying to port some bits to Idris 2 and I thought that these directives were not available any longer. Good to know that this is not the case!

**Comment by gallais** [comment] 2021-02-22 11:20
Given that we have other issues tracking the same problem and that
this got fixed with `%auto_implicits off`, I'll close this.

**Closed by gallais** 2021-02-22 11:20 UTC
Labels: language: generalisation, status: expected behaviour
