### ISSUE TITLE
Unable to solve constraint between same term

### ISSUE THREAD

**Issue by leesongun** [idris-lang/Idris2#2892] opened 2023-02-23 23:36 UTC
# Steps to Reproduce
`Idris 2, version 0.6.0-dc1b5387b`
```idris
m : Nat -> Nat -> Nat
m (S x) (S y) = S (m x y)
m _ _ = Z

l : (p:Bool) -> (a, b:Nat) -> (S(if p then a else b) = (if p then S a else S b))

p : (x, y : Nat) -> ((m x y) = (min x y))
p (S x) (S y) = trans (cong S $ p x y) $ l (x < y) x y
```

# Expected Behavior
The program compiles (with totality warnings).

# Observed Behavior
```
Can't solve constraint between: if x < y then x else y and if x < y then x else y.

source:8:42--8:55
 4 | 
 5 | l : (p:Bool) -> (a,b:Nat) -> (S(if p then a else b) = (if p then S a else S b))
 6 | 
 7 | p : (x, y : Nat) -> ((m x y) = (min x y))
 8 | p (S x) (S y) = trans (cong S $ p x y) $ l (x < y) x y
 ```

**Comment by gallais** [comment] 2023-02-24 00:26
Duplicate of #1809

**Closed by gallais** 2023-02-24 00:26 UTC

**Comment by dunhamsteve** [comment] 2023-02-24 01:15
See gallais' link for details.  You could pull this off if you were to use `ifThenElse` instead of `if_then_else_`, but you would have to define your own `min` in terms of `ifThenElse`:

```idris
m : Nat -> Nat -> Nat
m (S x) (S y) = S (m x y)
m _ _ = Z

l : (p:Bool) -> (a, b:Nat) -> (S(ifThenElse p a b) = (ifThenElse p  (S a)  (S b)))

%hide min

min : Nat -> Nat -> Nat
min x y = ifThenElse (x < y) x y

p : (x, y : Nat) -> ((m x y) = (min x y))
p (S x) (S y) = trans (cong S $ p x y) $ l ((<) x y) x y
p _ _ = ?hole
```

I only barely understand this stuff, but the situation might be changed by new core - the following is accepted by `yaffle --no-prelude`, but rejected by `idris2 --no-prelude`:

```idris
namespace Builtin
    public export
    data Equal : forall a, b . a -> b -> Type where
        [search a b]
        Refl : {0 x : a} -> Equal x x

    infix 6 ===, ~=~
    public export
    (~=~) : (x : a) -> (y : b) -> Type
    (~=~) = Equal
    
    public export
    (===) : (x : a) -> (y : a) -> Type
    (===) = Equal

data Bool = True | False
data Nat = Z | S Nat

foo : Bool -> Nat -> Nat -> Nat
foo True x y = x 
foo False x y = y 

bar : Bool -> Nat -> Nat -> Nat
bar True x y = x 
bar False x y = y 

example : foo b x y = bar b x y
example = Refl
```
