### ISSUE TITLE
Using interface methods in constraints creates strange issues

### ISSUE THREAD

**Issue by bijan-S** [idris-lang/Idris2#1276] opened 2021-04-05 03:55 UTC
https://gist.github.com/bijan-S/ec2d9b782844e62b52f12d9d6b9588ef

I'm not sure whether to label this as a feature request or a language problem, since I don't know whether this would be considered an intended feature or not.

I'm trying to create an interface which has a type constructor as a method (similar to "associated types" in Rust), like in this simplified example:
```idris
interface A where
  B : Type
  
  -- Method definitions using B...
```
This works fine. I then want to create another interface with a constraint of `A` that also puts a constraint on the instance of `B` in the implementation of `A`.

My first attempt to do this was something like this code (using `Semigroup` as an arbitrary example of a constraint):
```idris
interface A => Semigroup B => C where
  -- ...
```

I assumed that the value `B` in the constraint would automatically search for and find the instance of `A` given by the other constraint. 

# Expected Behavior

One of two possibilities, depending on how the interface system is meant to work:
1. The program type-checks fine and works as intended, or
2. The program fails to type-check, as this is not a feature of the interface system.

# Observed Behavior

The program type-checks without errors. However, the constraint on `B` doesn't seem to have actually been implemented:
```idris
test : C -> Semigroup B
test _ = %search
```
```
Error: While processing right hand side of test. Can't find an implementation for Semigroup B.
```

-------------

I then tried to solve this issue by explicitly naming and providing the `A` instance:
```idris
interface (a : A) => Semigroup (B @{a}) => D where
  -- ...
```

# Expected Behavior

Same as above.

# Observed Behavior

The interface definition immediately fails to type-check, giving the following confusing error:

```
Error: While processing right hand side of Constraint (Semigroup (B [$a])). When unifying B and B.
Mismatch between: __bind___con0 and a.
```

**Comment by gallais** [comment] 2021-04-05 10:33
This is a duplicate of #777

**Closed by gallais** 2021-04-05 10:33 UTC
