### ISSUE TITLE
failure to recompile modules, seemingly randomly

### ISSUE THREAD

**Issue by attila-lendvai** [idris-lang/Idris2#2033] opened 2021-10-19 17:47 UTC
let's call this file `bug.sh`:

```bash
IDRIS=idris2-0.5.1

cat > Module1.idr<< EOF
module Module1
export msg : String; msg="Hello world"
EOF

cat > module1.ipkg<< EOF
package pkg1
modules = Module1
EOF


cat > Main.idr<< EOF
module Main
import Module1

main : IO ()
main = do putStrLn ("The message is: " ++ msg)
EOF

cat > main.ipkg<< EOF
package app

main = Main
executable = test
EOF

${IDRIS} --build module1.ipkg
${IDRIS} --build main.ipkg

./build/exec/test

# overwrite msg
cat > Module1.idr<< EOF
module Module1
export msg : String; msg="New Message"
EOF

# this doesn't help, i.e. it's not due to low resolution of file modification times
sleep 1

# this helps
#rm build/ttc/Module1.tt*

${IDRIS} --build module1.ipkg
${IDRIS} --build main.ipkg

./build/exec/test
```

if i run it multiple times, it behaves inconsistently?!

```
$ ./bug.sh 
1/1: Building Module1 (Module1.idr)
2/2: Building Main (./Main.idr)
The message is: Hello world
1/1: Building Module1 (Module1.idr)
The message is: New Message

$ ./bug.sh 
1/1: Building Module1 (Module1.idr)
2/2: Building Main (./Main.idr)
The message is: Hello world
The message is: Hello world

$ ./bug.sh 
1/1: Building Module1 (Module1.idr)
2/2: Building Main (./Main.idr)
The message is: Hello world
1/1: Building Module1 (Module1.idr)
The message is: New Message

$ ./bug.sh 
1/1: Building Module1 (Module1.idr)
2/2: Building Main (./Main.idr)
The message is: Hello world
1/1: Building Module1 (Module1.idr)
The message is: New Message

$ ./bug.sh 
1/1: Building Module1 (Module1.idr)
2/2: Building Main (./Main.idr)
The message is: Hello world
1/1: Building Module1 (Module1.idr)
The message is: New Message

$ ./bug.sh 
1/1: Building Module1 (Module1.idr)
2/2: Building Main (./Main.idr)
The message is: Hello world
1/1: Building Module1 (Module1.idr)
The message is: New Message

$ ./bug.sh 
1/1: Building Module1 (Module1.idr)
2/2: Building Main (./Main.idr)
The message is: Hello world
The message is: Hello world
```

what's going on?

the actual context where this comes up is that i have moved `IdrisPaths.idr` into a separate module, so that i can generate it under `build/generated/`, and `idris2.ipkg` just imports it. but the updated `yprefix` never seems to reach the `idris2.ss` file, not even once when i was testing.

in this reproducer it sometimes happens. sorry if it's my fault, i have no clue what's going on here.

**Comment by gallais** [comment] 2021-10-19 18:18
I've observed similar issues when hacking on the compiler. I've sometimes needed 
to explicitly delete the `idris2` bin to make sure that recompilation deploys a
new one with the updated behaviour. Nice to have a small self-contained test case.

**Comment by attila-lendvai** [comment] 2021-10-29 19:15
to clarify: the `sleep` was not needed in my example either. i only added it to make it clear that it's not a timing issue (or at least not at that point).

**Comment by benhormann** [comment] 2021-10-29 20:37
It's more that I'm not sure if my script reproduces %100 on fast machines.

BTW: switching to `${IDRIS} --verbose -o bug2033 Module2.idr` also fixes it for 0.5.1, but not for HEAD!

**Comment by attila-lendvai** [comment] 2021-10-31 16:36
@benhormann i tried your version above (https://github.com/idris-lang/Idris2/issues/2033#issuecomment-954709566), and it behaves the same:

```
$ ./bug.sh 
1/2: Building Module1 (Module1.idr)
2/2: Building Module2 (Module2.idr)
The message is: Hello world
1/2: Building Module1 (Module1.idr)
The message is: Bug fixed!
$ ./bug.sh 
1/2: Building Module1 (Module1.idr)
2/2: Building Module2 (Module2.idr)
The message is: Hello world
The message is: Hello world
$ ./bug.sh 
1/2: Building Module1 (Module1.idr)
2/2: Building Module2 (Module2.idr)
The message is: Hello world
1/2: Building Module1 (Module1.idr)
The message is: Bug fixed!
$ ./bug.sh 
1/2: Building Module1 (Module1.idr)
2/2: Building Module2 (Module2.idr)
The message is: Hello world
1/2: Building Module1 (Module1.idr)
The message is: Bug fixed!
$ ./bug.sh 
1/2: Building Module1 (Module1.idr)
2/2: Building Module2 (Module2.idr)
The message is: Hello world
The message is: Hello world
$ ./bug.sh 
1/2: Building Module1 (Module1.idr)
2/2: Building Module2 (Module2.idr)
The message is: Hello world
The message is: Hello world
$ ./bug.sh 
1/2: Building Module1 (Module1.idr)
2/2: Building Module2 (Module2.idr)
The message is: Hello world
1/2: Building Module1 (Module1.idr)
The message is: Bug fixed!
```

**Comment by benhormann** [comment] 2021-10-31 22:36
From what I can deduce at a glance, Core.Hash creates a hash from exported declarations (i.e. not definitions). That's the immediate problem.

IMO, it'd be much simpler to hash only the source files. The hashes stored in association with each import can be a function of its source hash and deps hashes.
Currently `-Xcheck-hashes` is rehashing the compiled modules to calculate if those changed. It's better to read the source and deps hashes from the imported modules' headers, and recombine those to see if that matches what's stored in its own deps hash list (could even hash the list of hashed hashes 🤣).

We'd parse and hash the source files, read imported modules' headers, and that's all we need to know to do the build.
We can even skip hashing source files where the timestamp is older than the compiled module, as it does currently. You'd only need to specify `-Xcheck-hashes` if the timestamps of the source were somehow backdated.

Worst case there is a collision, and `make clean` will fix it (it'd be frustrating though).

**Comment by attila-lendvai** [comment] 2021-12-03 13:42
any hope for fixing this?

it's blocking https://github.com/idris-lang/Idris2/pull/1990 and new build system PR's are coming in (e.g. https://github.com/idris-lang/Idris2/pull/2153) that, when merged, will clash with it.

**Comment by mattpolzin** [comment] 2021-12-07 06:13
This is an interesting issue because I think there are a few possible interpretations for what is going on here. I've been playing around and I think I have _some_ but not all of those answers.

First of all, the behavior should definitely be consistent each run of the test script -- I was able to reproduce the erratic behavior with v0.5.1 of the compiler but not with HEAD of the main branch, so either there was a fix for that problem or else the problem has become less common.

Second, this is a bit of an ambiguous case where there are two package manifests in the same folder looking at the same files so what the compiler appears to be doing is (a) building Module1.idr as part of the first package and (b) ignoring it when building the second package but still relying on the TTC data that just happens to be in the same build folder.

Given how Idris is excluding Module1.idr from the second package, the behavior of "always print Hello world" is correct (you should never see "New message"). That's because modules from outside of the current package are only determined to have changed when their public interface changes and Module1.idr does not `public export` its `msg` function.

There are two ways you can tweak what the current Idris compiler does here and then there's also an opportunity for making the compiler's behavior more intuitive.

1. If you make `msg` publicly exported, Idris will use its definition in the interface hash and when you change the message Idris will rebuild Module1 in addition to Main and the message printed out will change for the second execution of the test script.
2. If you explicitly tell Idris that Module1 is part of the second package (by adding it to that package manifest's `modules` list), that will also cause Module1 to rebuild and you will see "New Message" consistently in the output from the second execution of the test script.

So that leaves the question of what would be the most intuitive behavior for the compiler in this situation (two package manifests in the same folder looking at the same source and build directories with one or both package's omitting an explicit `modules` entry). Do we want the second package to co-own the first Module? Do we even want to explicitly support this kind of package structuring (I'd be interested to hear the benefits since I have not don't this before myself)? Do we want the compiler to give a warning or throw an error (what would we call this problem)?

Curious what others think. Also please let me know if I  have missed part of the problem in my writeup. I apologize that i largely ignored the evolution of this thread and chose to focus on the original bug report, but I think that anything not readily related to the exact bug as reported will be better suited by its own ticket so we can give it proper attention.

**Comment by attila-lendvai** [comment] 2021-12-07 07:58
> Do we even want to explicitly support this kind of package structuring (I'd be interested to hear the benefits since I have not don't this before myself)?

FTR, what i did here is much more a newbie error than anything deliberately designed.

**Comment by benhormann** [comment] 2021-12-07 21:12
> That's because modules from outside of the current package are only determined to have changed when their public interface changes

@mattpolzin This also occurs when it is in the same package.

ModTree and ProcessIdr have barely changed since v0.5.1, so observed differences are incidental.

---

@attila-lendvai I have an idea of what the build process should look like, but haven't tried to implement it yet. Dropping the interface hash would cause recompilation when external modules have private changes (so that'd be a design change).
I also haven't looked into why the code generation produces the old value, it's like the old definition is cached.

It's not really blocking your PR, just your current strategy. It'd be better to avoid recompiling with one line changed, IMO.

**Comment by mattpolzin** [comment] 2021-12-08 04:41
> This also occurs when it is in the same package.

@benhormann when you say "this also happens" can you be more specific? If you are referring to erratic compilation (i.e. sometimes a module is recompiled and other times it is not) then that is what I am having a hard time reproducing using the test script from the original post. I can either consistently get recompilation using the two strategies I described in my response or consistently avoid recompilation owing to the module being built by the first package manifest and not being rebuilt by the second manifest.

I'm not surprised if there is a problem here still, but I may need to find a different way to reproduce it.

I see the script you shared only uses 1 package -- I'll give that a run. I suspect what you are saying I will find is that even with only 1 package Idris is going to ignore changes to Module1; I am curious if this changes if you explicitly specify Module1 (and 2) as modules in the package manifest under a `modules` entry. If so, we might be able to make this behavior more consistent by figuring out what Idris is doing differently when it determines what modules to build with or without a `modules` entry in the manifest.

**Comment by benhormann** [comment] 2021-12-08 19:48
Module1 never gets skipped, so if only the interface matters then Module2 shouldn't need recompiled?

On my phone (a sufficiently slow machine) the output of the scripts is consistent:
v0.5.1 prints Bug fixed / New message.
HEAD prints Hello world.

Note that with v0.5.1, it does **not** recompile Module2 yet prints the updated message.
So on fast machines the bug is: doesn't always reload definitions after recompilation?

With HEAD, running build a third time doesn't produce the correct message either. The message is inlined into Module2 !!

**Comment by mattpolzin** [comment] 2021-12-09 01:00
ok, I've been playing with the second test script which removes the variable of there being multiple package manifests. 

> The message is inlined into Module2 !!

You hit on something here that I played with a bit as well and indeed if you specify `%noinline` before the definition of `msg` in Module1 then you get the "Bug fixed!" message whereas if you don't then you get the "Hello world" message (with HEAD of the compiler, at least).

So maybe one problem is that the compiler is literally inlining a definition that it doesn't include in the interface of the module. Maybe we need to tell the compiler to avoid inlining definitions that are not `public export` and/or add to the hash for definitions that we do inline.

**Comment by mattpolzin** [comment] 2021-12-09 01:03
I think it makes sense to me that non public definitions would be off limits for inlining to begin with (like even an explicit `%inline` directive would not be allowed).

**Comment by mattpolzin** [comment] 2021-12-09 01:16
Now things are getting interesting (or rather I am starting to see interesting results with my own eyes). With a `%noinline` flag applied to `msg`, I am starting to see inconsistent results from one run to the next.

**Comment by benhormann** [comment] 2021-12-09 07:02
I also tested `%noinline`, but isn't it a codegen directive? Exported definitions should never be inlined (at this _module_ level — in TTC files), whereas the codegen can opt to inline it.

If you are still getting inconsistencies with `%noinline`, that suggests there is a timing/caching issue. Try replacing `${IDRIS} --build bug2033.ipkg` with:
```
# build modules
${IDRIS} -c Module2.idr
# generate code
${IDRIS} -o bug2033 Module2.idr
```

---

Public vs non-public doesn't really matter, all definitions should be stored in their module (exclusively). Only non-exported definitions are eligible for inning, but does it ever make sense to do so?

**Comment by mattpolzin** [comment] 2021-12-09 17:52
> If you are still getting inconsistencies with `%noinline`, that suggests there is a timing/caching issue.

Agreed. I wanted to track that down first to eliminate problems one at a time. [This](https://github.com/idris-lang/Idris2/pull/2188) appears to get rid of the inconsistent behavior with `%noinline` used (it was _very_ edge-case but it meant the test script was not giving particularly good feedback and the fix is strictly beneficial).

Now I am going to work on the rest of this (starting with whether we are treating inlining, public, and module interface hashes correctly relative to each other).

**Comment by mattpolzin** [comment] 2021-12-09 18:28
> Exported definitions should never be inlined (at this module level — in TTC files), whereas the codegen can opt to inline it.

I have not read over the inlining code yet (next on my list), but on a run when the bug was encountered I checked the TTC for Module2 and the result would seem to indicate that the compiler frontend does do some inlining sometimes (here's a snippet from Module2's TTC file)
```
??Module2?????The message is: Hello world
```

**Comment by mattpolzin** [comment] 2021-12-09 20:27
Inlining does occur prior to TTC generation, including the heuristic that was causing Module1.msg to be inlined into Module2.

I've updated the code in the aforementioned PR so that it only heuristically inlines public functions -- I am not sure how much of a bummer this is from the perspective of performance but that heuristic was too eager before IIUC.

**Comment by mattpolzin** [comment] 2021-12-09 21:19
> Either approach should work: adding public export defs to the hash, or never inlining imported defs.

The former is already done (public exports are added to the hash). The thing that would change behavior would be adding unforced inlines (where the compiler decides its a good idea without being told to) to the hash, but adding those to the hash would be untrue to the intention of the programmer and also require a bit of thinking on feasibility because inlining occurs when using a def, after it has already been written to its own TTC if it is from a different module. For that reason, I went with the approach of not inlining non-public definitions.

> The way it SHA2 hashes the TTC files is messed up. That process wants an overhaul, even if you've fixed part of it.

I certainly noticed some messy inconsistent things happening around building (it'll build things multiple (and differing numbers) of times. I am not going to touch that as part of this ticket to keep the scope of my fix small. That means if I can get the end result of recompilation to be consistent and well-behaved (no race conditions and no possibility of using old versions of definitions from previous inlining) then I am going to close this issue out.

The remaining quirks of compilation and recompilation deserve attention as their own ticket(s) in my opinion.

**Comment by benhormann** [comment] 2021-12-09 22:42
When / why is inlining/caching another modules definition a good idea? If it can be avoided but allow/instruct the codegen to inline it, wouldn't that be best?

Should Module1.msg be `public export`ed? That also seems to fix the problem (at the expense of recompiling both modules). Makes more sense than adding `%noinline`.

**Comment by mattpolzin** [comment] 2021-12-09 23:07
> When / why is inlining/caching another modules definition a good idea?

It would be a good idea in the same situations it is a good idea within a single module, except for the important fact that inlining another module's definitions causes complexity if not inherent problems with respect to maintaining a module's public interface.

> If it can be avoided but allow/instruct the codegen to inline it, wouldn't that be best?

I do think that inlining that occurred later in the process by individual codegens would be more precise and could be more sweeping -- but it then requires implementation multiple times and it doesn't have a positive impact on TTC size or downstream Idris compilation and even runtime elaboration (of an upstream module where inlining has been applied). In short, I think both are beneficial. Downstream inlining is almost certainly done by Scheme anyway, but not all backends are going to have that as an explicit optimization.

> Should Module1.msg be `public export`ed?

With the fix I ended up creating a PR for, the bug is fixed no matter what you want to do with `Module1.msg` --
1. If you only `export` it, Module1 will be referenced anywhere `msg` is used in Module2 and Module2 does not necessarily need to be rebuilt when `Module1.msg` changes.
2. If you `public export` it, `Module1.msg` will be inlined into Module2 owing to an inlining heuristic and changes to `Module1.msg` will result in recompilation of both modules so that the inlined string stays up to date.
3. If you `%inline` it, the net result is the same as if you `public export` it except the heuristic is not relied upon because you are forcing inlining.
4. If you `%noinline` it, the net result is the same as if you just `export` it except if you `public export` it as well then you end up recompiling both modules when `Module1.msg` changes despite the fact that the definition is not being inlined.

The other quirks of compilation that i mentioned I was not tackling now still mean that you may get differing amounts of recompilation, including situation (1) above resulting in recompiling both modules, but this is inconsistent (sometimes both modules are recompiled, other times only Module1 is recompiled) -- regardless, the changes I made seem to have the desired effect on the end result.

**Comment by benhormann** [comment] 2021-12-09 23:23
Good job, I wouldn't have figured out how to do that.

I agree, what remains is a separate issue.

**Comment by attila-lendvai** [comment] 2021-12-25 17:32
i can confirm that when i'm rebasing https://github.com/idris-lang/Idris2/pull/1990 on this PR, then it fixes my headaches of not incorporating the changes made to `IdrisPaths.idr` into the final executable.

**Closed** 2022-01-21 10:26 UTC
Labels: Installation Issue, status: confirmed bug
