### ISSUE TITLE
using `@` in patterns leads to `...is not accessible in this context` when it shouldn't matter

### ISSUE THREAD

**Issue by falsifian** [idris-lang/Idris2#2249] opened 2022-01-04 17:32 UTC
This gives an error:

```
data T : Nat -> Type where
  MkT : (n : Nat) -> T n

f : T n -> Nat
f i@(MkT m) = m
```

```
Error: While processing right hand side of f. m is not accessible in this
context.

13bad:5:15--5:16
 1 | data T : Nat -> Type where
 2 |   MkT : (n : Nat) -> T n
 3 | 
 4 | f : T n -> Nat
 5 | f i@(MkT m) = m
                   ^
```

but this doesn't (I just removed the `i@`):

```
data T : Nat -> Type where
  MkT : (n : Nat) -> T n

f : T n -> Nat
f (MkT m) = m
```

Similarly, this gives an error:

```
data T : Nat -> Type where
  MkT : (n : Nat) -> T n

f : T n -> Nat
f i@(MkT _) = case i of { MkT m => m }
```

```
Error: While processing right hand side of f. n is not accessible in this
context.

15:5:15--5:39
 1 | data T : Nat -> Type where
 2 |   MkT : (n : Nat) -> T n
 3 | 
 4 | f : T n -> Nat
 5 | f i@(MkT _) = case i of { MkT m => m }
                   ^^^^^^^^^^^^^^^^^^^^^^^^
```

but this doesn't:

```
data T : Nat -> Type where
  MkT : (n : Nat) -> T n

f : T n -> Nat
f i = case i of { MkT m => m }
```

(The latter example from @bkomuves, assuming that's the same as the Discord user.)

This is using idris2 compiled at 3c532ea35 plus my PR #2100 which should not be related.

**Comment by gallais** [comment] 2022-01-05 09:28
This seems like a duplicate of #490

**Closed by gallais** 2022-01-05 09:28 UTC
