### ISSUE TITLE
REPL `:t` and `:doc` remove some variable names

### ISSUE THREAD

**Issue by ngeiswei** [idris-lang/Idris2#2504] opened 2022-05-26 08:26 UTC
# Steps to Reproduce

1. Go to the Idris2 REPL
```bash
$ idris2
```
2. Import `Data.Vect.Quantifiers` module
```idris2
:module Data.Vect.Quantifiers
```
3. Display type of `Data.Vect.Quantifiers.All.all`
```idris2
:t Data.Vect.Quantifiers.All.all
```

# Expected Behavior

The type signature of `all` should contain the variable `dec`, as in

https://github.com/idris-lang/Idris2/blob/37c9c06f72f8e2fdc3a2aa18883263d7ba6d9471/libs/base/Data/Vect/Quantifiers.idr#L85

# Observed Behavior

Instead it displays

```idris2
Data.Vect.Quantifiers.All.all : ((x : a) -> Dec (p x)) -> (xs : Vect n a) -> Dec (All p xs)
```

which in itself is not a problem, it could even be desirable as it is more compact, however the problem comes when using `:doc` because then the comment mentions `dec` which is missing from the type signature.

**Comment by gallais** [comment] 2022-05-26 08:31
This is a duplicate of #1387

**Closed by gallais** 2022-05-26 08:31 UTC
