### ISSUE TITLE
Javascript: Allow node: lambdaRequire to use local javascript files.

### ISSUE THREAD

**Issue by Invisible-Rabbit-Hunter** [idris-lang/Idris2#849] opened 2020-12-15 04:57 UTC
In the javascript backend, trying to require (via `node:lambdaRequire:./localFile`) a local javascript file results in incorrectly generated javascript, specifically the period is placed in the name of the `__require_._localFile` variable, which is a syntax error.
# Steps to Reproduce
Compile 
```idris
module Main

%foreign "node:lambdaRequire:./compat:compat"
compat : PrimIO ()

main : IO ()
main = primIO compat
```
via the node backend.

# Expected Behavior
The generated javascript is syntactically correct.
For example a name like this:
```javascript
const __require__compat = require('./compat');
```
# Observed Behavior
The following line is generated:
```javascript
const __require_._compat = require('./compat');
```
Note the period in the middle of the name.

**Comment by michaelmesser** [comment] 2020-12-24 03:03
I think this is easy to fix. I will make a PR.

**Comment by michaelmesser** [comment] 2020-12-24 21:59
The problem is [requireSafe](https://github.com/idris-lang/Idris2/blob/910711afe994166c41fa329086872713ad6f0f38/src/Compiler/ES/ES.idr#L59) is using an incomplete blacklist. Since node caches requires, is there even a need to store it in a variable? I believe we can just require it every time. If we still want to use variables, I will replace the blacklist with a whitelist and add a hash at the end to ensure there won't be duplicate names for the same string.

**Comment by michaelmesser** [comment] 2020-12-24 22:16
By my measurement, it takes 0.000109444ms (109.444 ms for 1,000,000) to require a module after it has already been required. I am fine to implement it either way.

**Comment by michaelmesser** [comment] 2020-12-24 23:15
My previous idea would require the user to type out the escape sequences which would be ideally avoided.

Looking at this more, I am not sure why `lambdaRequire` exists at all.

Instead of:
```idris
%foreign "node:lambdaRequire:fs:fp=>__require_fs.fstatSync(fp.fd, {bigint: true}).size"
prim__fileSize : FilePtr -> PrimIO Int
```
can't one just use lambda and call require in the lambda like this:

```idris
%foreign "node:lambda:fp=>require('fs').fstatSync(fp.fd, {bigint: true}).size"
prim__fileSize : FilePtr -> PrimIO Int
```

Node caches requires. I measured that requiring an already loaded module only has a 0.000172294ms penalty (4,000,000 requires in 689.177 ms).

@rbarreiro Git shows that you last edited the portions of the code related to lambdaRequire. Can you tell me why it was added? Is there any reason not to remove it?

**Comment by gallais** [comment] 2021-02-17 10:09
I guess this was fixed by removing `lambdaRequire` altogether.

**Closed by gallais** 2021-02-17 10:09 UTC
