### ISSUE TITLE
Referring to an already-defined data constructor

### ISSUE THREAD

**Issue by bts8394** [idris-lang/Idris2#2660] opened 2022-09-14 17:08 UTC
Hi, I'm trying Idris for the first time and really enjoying it, using version 0.5.1-36918e6. I was going through the tutorial and found an example that looked like a polynomial monad so I wanted to try and make one, but my Idris guru said I couldn't make a data constructor with a dependent sum type in the codomain so I tried to unwind it into Pi' and Pi'' in the code below. However, I get an error saying -Undefined name Pi'-. Is it not possible for data constructors to refer to previously defined constructors? Thanks so much!
 
```idris
data V : Type
data T : V -> Type

data V : Type where
    N : V
    Pi : (a : V) -> (b : T a -> V) -> V

data T : V -> Type where
    Pi' : T (Pi a b) -> T a
    Pi'' : (x : T (Pi a b)) -> T (b (Pi' x))
```

**Comment by gallais** [comment] 2022-09-14 17:31
This is a duplicate of #1131

**Closed by gallais** 2022-09-14 17:31 UTC
