### ISSUE TITLE
Very slow typechecking of a seemingly simple definition

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#2191] opened 2021-12-12 10:52 UTC
Here is the source, sorry it isn't minimised
https://github.com/alexhumphreys/idrall/blob/main/Idrall/Lexer.idr

# Steps to Reproduce
speed.sh:
```sh
rm build/ttc/Idrall/Lexer.ttc
time idris2 --build idrall.ipkg --timing
```

# Expected Behavior

Typechecks quickly (< 1 second)

# Observed Behavior

Typechecks slowly (~ 4 second)
According to idris2's timing, `Check RHS Idrall.Lexer:90:1--92:40: 2.953s` takes up almost all the time.

**Comment by bkomuves** [comment] 2021-12-13 11:53
This looks a duplicate of #2032 (Date.Vect re-exports Data.Fin).

As temporary fix, you `%hide Fin.fromInteger` at the beginning of the module.

**Comment by gallais** [comment] 2021-12-16 15:15
I can confirm that with current HEAD I get:

```
TIMING +++ Check RHS Idrall.Lexer:90:1--92:40: 0.002s
```

**Closed** 2021-12-16 15:15 UTC
Labels: performance
