### ISSUE TITLE
Truncated empty-lines in multi-line strings

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1951] opened 2021-09-23 10:28 UTC
# Steps to Reproduce
```idris
$ cat StringInt.idr
foo1, foo2 : String

foo1 = """
  One

  Two
  """

foo2 = """
  One
  
  Two
  """
$ idris2 StringInt.idr
```

# Expected Behavior
`foo1` and `foo2` are the same.

# Observed Behavior
```
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.4.0-6780874d2
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/      Type :? for help                     

Welcome to Idris 2.  Enjoy yourself!
1/1: Building StringInt (StringInt.idr)
Main> foo1
"One
Two"
Main> foo2
"One

Two"
Main> 
```

On the one hand, this is expected because in `foo1`, the empty lines don't have the same amount of indentation.
On the other hand, some editors automatically truncate trailing spaces, which make it impossible to write the correct `foo2` in those editors.

The workaround is to not indent multiline strings with empty lines. 

This is really a design decision, but we've had a quick discussion (on Discord) and at least some people thought it ought to be a bug.

**Comment by buzden** [comment] 2021-09-23 11:40
Is this a duplicate of #1626?

**Closed** 2021-09-23 12:07 UTC
Labels: status: duplicate, status: confirmed bug, syntax, implem: parsing, language: literals, implem: string
