### ISSUE TITLE
Case splitting a Vect after a with clause causes unification error

### ISSUE THREAD

**Issue by jakeelituv** [idris-lang/Idris2#751] opened 2020-10-21 16:12 UTC
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
Define a function on a `Vect`, create a with clause, pattern match on any `Vect` afterwards. The view used seems to be irrelevant. Example:

```
test : Vect n a -> Int
test xs with (length xs < 0)
  test xs | True = ?test_rhs_rhs_1
  test xs | False = ?test_rhs_rhs_3
```

No errors, now case split either `xs`:

```
test : Vect n a -> Int
test xs with (length xs < 0)
  test xs | True = ?test_rhs_rhs_1
  test [] | False = ?test_rhs_rhs_4
  test (x :: xs) | False = ?test_rhs_rhs_5
```

```
While processing left hand side of with block in test at Test.idr:57:3--58:3:
When unifying Vect 0 ?a and Vect ?n ?a
Pattern variable n unifies with:
	0
at:
55	test xs with (length xs < 0)
```

**Comment by gallais** [comment] 2021-11-24 18:26
This is a duplicate of #733.

**Closed by gallais** 2021-11-24 18:26 UTC
Labels: status: confirmed bug, language: with, interactive: case
