### ISSUE TITLE
Non-productive infinite loop passing type checker

### ISSUE THREAD

**Issue by reswatson** [idris-lang/Idris2#1846] opened 2021-08-18 21:54 UTC
# Steps to Reproduce

```
total
powerStreamBug : Nat -> Inf (Stream Nat) -- ? bug ...circular, not productive
powerStreamBug n = (map (mult n) (powerStreamBug n))
```

Then type check

# Expected Behavior

Should not type check

# Observed Behavior

Type checks 

Note that the following correct version of the code requires the Inf: 

```
total
powerStream' : Nat -> Inf (Stream Nat)
powerStream' n = n :: (map (mult n) (powerStream' n))
```

**Comment by gallais** [comment] 2021-08-18 23:27
This seems like a duplicate of #806

**Closed** 2021-08-20 13:53 UTC
Labels: status: duplicate
