### ISSUE TITLE
Exhaustivity checking doesn't work for sigma type

### ISSUE THREAD

**Issue by olynch** [idris-lang/Idris2#2739] opened 2022-10-30 23:18 UTC
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce

The following code doesn't compile

```idris
data Indexed : Type -> Type where
  I : Int -> Indexed Unit

bug : (a : Type ** Indexed a) -> Int
bug (_ ** I k) = k
```

# Expected Behavior

This code typechecks.

# Observed Behavior

I get the error:

```
- + Errors (1)
 `-- src/Bug.idr line 4 col 0:
     bug is not covering.
     
     Bug:4:1--4:37
      1 | data Indexed : Type -> Type where
      2 |   I : Int -> Indexed Unit
      3 | 
      4 | bug : (a : Type ** Indexed a) -> Int
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     
     Missing cases:
         bug (_ ** _)
```

**Comment by gallais** [comment] 2022-10-30 23:40
It's a known issue (it's 11:40pm so can't be bothered to look it up in the bug tracker).
Notice that the generated case tree proceeds by case analysis on the type:

```
:di bug
Main.bug
Arguments [{arg:0}]
Compile time tree: case {arg:0} : (a : Type ** Indexed a) of
  MkDPair {e:0} {e:1} {e:2} {e:3} => case {e:2} : Type of
    Unit => case {e:3} : (\a => Indexed a) {e:2} of
      I {e:4} => {e:4}
```

**Comment by olynch** [comment] 2022-10-30 23:41
OK, I'm happy for this to be closed then; I trust you that there's another issue.

**Comment by CodingCellist** [comment] 2022-11-01 16:13
Duplicate of #2639 iiuc  : )

**Closed by CodingCellist** 2022-11-01 16:13 UTC
Labels: status: duplicate, safety: coverage, implem: pattern-matching
