### ISSUE TITLE
Unable to parse `Lazy` when it precedes a $

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#2913] opened 2023-03-05 14:44 UTC
Might be related to #1445 and  #2599.

# Steps to Reproduce
```idris
works : (Lazy (Maybe a), a)
--fails : (Lazy $ Maybe a, a)
```

# Expected Behavior
Uncommenting the second line parses and type-checks.

# Observed Behavior

Uncommenting it gives an error:
```
 Expected a type declaration.
     
     :3:7--3:8
      1 | works : (Lazy (Maybe a), a)
      2 | 
      3 | fails : (Lazy $ Maybe a, a)
```

Relatedly, putting this line in a `failing` block also fails, with the same error:
```
 line 3 col 8:
     Expected a type declaration.
     
     Lazy:3:9--3:10
      1 | works : (Lazy (Maybe a), a)
      2 | failing
      3 |   fails : (Lazy $ Maybe a, a)
                  ^
```

**Comment by buzden** [comment] 2023-03-05 14:53
BTW this applies to `Inf` and `Delay` too

**Comment by gallais** [comment] 2023-03-05 14:53
This is indeed a duplicate of #2599

**Closed by gallais** 2023-03-05 14:53 UTC
Labels: implem: parsing, language: failing
