### ISSUE TITLE
Confusing behaviour in fromInteger

### ISSUE THREAD

**Issue by claymager** [idris-lang/Idris2#1541] opened 2021-06-11 20:55 UTC
#1539 seems to have introduced a regression: everything works with the previous master commit ec1e7c0d, but  unexpected behaviour is shown on the next commit  663a8381.

# Steps to Reproduce

This module sets up the bounded Nat called Size, and declares a `fromInteger` that coerces anything over the upperbound to its max value.

On its own, this works as expected.

```idris

module Size

import Data.Maybe
import Data.Nat

MaxSizeNat : Nat
MaxSizeNat = 100

public export
record Size where
  constructor MkSize
  size : Nat
  0 sizeOk : LTE n MaxSizeNat

mkSize : (n : Nat) -> {auto 0 ok : LTE n MaxSizeNat} -> Size
mkSize n = MkSize n ok

maxSize : Size
maxSize = mkSize MaxSizeNat {ok=lteRefl}

export
mkSizeMay : Nat -> Maybe Size
mkSizeMay k with (isLTE k MaxSizeNat)
  mkSizeMay k | (Yes prf) = Just $ mkSize k
  mkSizeMay k | (No contra) = Nothing

export
fromInteger : Integer -> Size
fromInteger = fromMaybe maxSize . mkSizeMay . fromInteger
```

The issue arises when idris2 tries to build this:
```idris
module Usage

import Size

upperbound : Size
upperbound = 400

explicit : Size
explicit = fromInteger 42

-- elaborated : Size
-- elaborated = 42

```
# Expected Behavior

All three cases behave identically.

Historically, they all pass, without requiring `Usage` to import `Data.Maybe` and `Data.Nat`.

# Observed Behavior

`elaborated` fails when uncommented, with 
```Error: While processing right hand side of elaborated. Undefined name Data.Maybe.fromMaybe. ```

**Comment by edwinb** [comment] 2021-06-12 12:24
It now fully evaluates `fromInteger`rather than just evaluating the exported names, which is necessary for properly pattern matching on the LHS. So if `fromMaybe` is needed, it's going to be needed to do a proper linearity check since we need the type for that.

Sorry, this is annoying. But it is expected as a result of the fix, and the fix is necessary.

**Comment by edwinb** [comment] 2021-06-12 12:36
One possibility, I suppose, is that `Size` should use `import public` for `Data.Maybe`. Another would be for us not just not reduce the `fromInteger` if it's only an `export` but then you wouldn't be able to pattern match on a `Size` as an integer.

**Comment by edwinb** [comment] 2021-06-12 13:17
Hmm, actually, on the LHS it's necessary but on the RHS it's merely an optimisation. Possibly it should be LHS only, therefore. You'd still get the error message on the LHS without the `public import`, but in that situation I think it would genuinely be an error because we wouldn't be able to compile it properly.

**Comment by claymager** [comment] 2021-06-12 14:10
On the RHS, the library author can get the optimisation if its available by uising `%inline`, right? Or is something else going on?

**Comment by edwinb** [comment] 2021-06-12 14:19
It's more a compile time optimisation that was intended to reduce repeated evaluations of constants. But, if you're in that situation, you probably ought to know that's what's going on and import the necessary names...

**Comment by edwinb** [comment] 2021-06-13 13:52
I'm going to close this since I think the behaviour now is as good as it can be - I moved it to LHS only. Though at some point I'll see if we can make linearity checking possible in more cases, without knowing the types of unimported things (maybe if there's no linear bindings, for example).

**Closed by edwinb** 2021-06-13 13:52 UTC
