### ISSUE TITLE
INTERNAL ERROR: build/ttc/Test.ttc: File Not Found

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#43] opened 2020-05-20 12:48 UTC
<a href="https://github.com/gallais"><img src="https://avatars1.githubusercontent.com/u/1094905?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gallais](https://github.com/gallais)**
_Saturday Apr 04, 2020 at 08:34 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/264_

----

Very easy to reproduce this internal error:	

```shell
touch Test
idris2 Test
```

gives us:

> Uncaught error: INTERNAL ERROR: build/ttc/Test.ttc: File Not Found

**Comment by sheerluck** [comment] 2020-09-23 14:29
This error stops me right at Docs » A Crash Course in Idris 2 » Getting Started » Checking Installation  😕

**Comment by gallais** [comment] 2020-09-23 14:36
Is the file you are creating missing the `.idr` extension by any change?
I reproduced this error today for the first time in ages because I had
forgotten to type the `.idr` part.

**Comment by sheerluck** [comment] 2020-09-23 15:24
oh
Thank you

**Comment by gallais** [comment] 2020-09-24 15:03
Ha! Fixed by 416b9578e51bf365d3c874131c30d74d6ff5993b! :partying_face:

**Closed** 2020-09-24 15:03 UTC
Labels: cli: repl, internal error
