### ISSUE TITLE
"Erased argument" error in pattern match on Data.DPair.Subset

### ISSUE THREAD

**Issue by polendri** [idris-lang/Idris2#661] opened 2020-09-10 13:02 UTC
# Steps to Reproduce

```idris
import Data.DPair

data SBool : Bool -> Type where
     SFalse : SBool False
     STrue  : SBool True

sNot : (Subset.Subset Bool SBool) -> Bool
sNot (Element False SFalse) = True  -- Fails on v2.1.0 with "Can't match on SFalse (Erased argument)"
sNot (Element True STrue) = False

sNot' : (x : Bool) -> (0 s : SBool x) -> Bool
sNot' False SFalse = True   -- Without using Subset, matching on the erased argument succeeds.
sNot' True  STrue  = False  -- But should this not be equivalent to using Subset?
```

# Expected Behavior

Pattern-matching on `Subset` does not cause "erased argument" errors, since the value of the erased type is inferrable from the other value.

# Observed Behavior

The "Can't match on SFalse (Erased argument)" error occurs, unless it's worked around by adding an intermediate definition which matches on both components inside the `Subset` type:

```
import Data.DPair

data SBool : Bool -> Type where
     SFalse : SBool False
     STrue  : SBool True

sNot : (Subset.Subset Bool SBool) -> Bool
sNot (Element x y) = sNot' x y where
  sNot' : (b : Bool) -> (0 s : SBool b) -> Bool
  sNot' False SFalse = True
  sNot' True STrue = False
```

This workaround makes `Subset` a cumbersome type to use.

@gallais notes:

> Strange because [this](https://github.com/idris-lang/Idris2/blob/master/src/Core/TT.idr#L524) works and it's doing pattern-matching on a
forced runtime irrelevant argument [paired up inside of a record](https://github.com/idris-lang/Idris2/blob/master/src/Core/TT.idr#L476).
>
> Is it because SizeOf is an ad-hoc definition rather than reusing
a generic data structure like Subset?

**Comment by gallais** [comment] 2021-02-01 14:43
I was thinking about helping the matcher by marking these patterns as forced
but that also leads to a `Can't match` error. :(

```idris
sNot : Subset Bool SBool -> Bool
sNot (Element False .(SFalse)) = True
sNot (Element True .(STrue)) = False
```

**Comment by gallais** [comment] 2021-02-22 12:09
This is a duplicate of #499

**Closed by gallais** 2021-02-22 12:09 UTC
Labels: implem: pattern-matching, language: quantity, status: confirmed bug
