### ISSUE TITLE
eliminating equality on linear vars

### ISSUE THREAD

**Issue by jonleivent** [idris-lang/Idris2#214] opened 2020-05-31 23:34 UTC
Using Version 0.2.0-59800e1f4

```idris
module Funny

funny1 : (1 x : a) -> (1 y : a) -> (0 e : x = y) -> (a, a)
funny1 x y e = (x, y) {-typechecks!-}

funny2 : (1 x : a) -> (1 y : a) -> (0 e : x = y) -> (a, a)
funny2 _ _ Refl = ?wont_typecheck
```
 produces the error:
```
Funny.idr:7:1--9:1:There are 2 uses of linear name (implicit) _
```

I admit confusion about when linearity conflicts with equality.  So I don't know what should happen.  If funny1 is OK, why should eliminating on the equality in funny2 make it not OK?  Even if variables are used instead of underscores.

**Comment by ziman** [comment] 2020-06-01 07:44
Besides, the error message is strange; there shouldn't be two uses of a linear name there.

**Comment by edwinb** [comment] 2020-06-01 09:35
The two uses of the linear name error is because `x` and `y` are made to be the same by `Refl`, so it's equivalent to an LHS of:

```
funny2 x x Refl
```

So on the LHS, `x` is used twice, and `y` isn't used at all. This is a tricky one, because we now really have to use `x` exactly twice on the RHS, and we don't have a way of expressing that yet, hence the current behaviour. So I think this is doing the right thing as things currently stand, even if it's inconvenient.

**Comment by clayrat** [comment] 2020-06-01 23:48
I guess this is where rigcount work by @andrevidela could be useful?

**Comment by andrevidela** [comment] 2020-06-02 10:48
~ish.

First of all, I agree that the current behaviour seem to be the correct one. 

Abstracting over RigCount should allow us to implement different semirings with different semants. Using a `Nat` semiring (with an unrestricted value) we might be able to get back the expressivity that we are looking for.

I think the best way to get this right is to count the number of uses on the LHS and compare it to the sum of the multiplicities declared in the type signature for terms that have been proven equal. This way if we have naturals we get

```
funny : (1 x : a) -> (1 y : a) -> (0 e : x = y) -> (a, a)
funny x x = ?x_has_multiplicy_2
```
because there are 2 uses of x and x is given twice in the type signature and `1 + 1 = 2`

however with 0,1, ω we could get 2 uses of x on the LHS but its multiplicity would be `1 + 1 = ω` and `2 ≠ ω` which is the behaviour we want.

So I guess we can close this and revisit it later once we have a better grasp on linearity and different semirings for multiplicities.

**Comment by edwinb** [comment] 2020-06-06 21:45
I'm going to close this as expected behaviour, but we'll probably want to revisit this sort of thing later when we have more experience with different semirings.

**Closed by edwinb** 2020-06-06 21:45 UTC
Labels: Expected Behaviour
