### ISSUE TITLE
Naming issue when checking type of hole when function uses arguments with same names as those defined in the constructors

### ISSUE THREAD

**Issue by jakeelituv** [idris-lang/Idris2#813] opened 2020-12-03 19:34 UTC
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
From [`TinyIdris Core.TT`](https://github.com/edwinb/SPLV20/blob/master/TinyIdris-v2/src/Core/TT.idr)

```
data SubVars : List Name -> List Name -> Type where
     SubRefl  : SubVars xs xs
     DropCons : SubVars xs ys -> SubVars xs (y :: ys)
     KeepCons : SubVars xs ys -> SubVars (x :: xs) (x :: ys)

subElem : {idx : Nat} -> (0 p : IsVar name idx xs) ->
          SubVars ys xs -> Maybe (Var ys)
subElem p SubRefl = ?subElem_rhs_1
subElem p (DropCons x) = ?subElem_rhs_2
subElem p (KeepCons x) = ?subElem_rhs_3
```

Checking the type of `?subElem_rhs_2 `yields  `x : SubVars ys ys`, which incorrectly indicates the two lists as parameters in SubVars are equal.

# Expected Behavior

If instead I define subElem as follows, replacing `xs` with `ws` and `ys` with `zs` so that the names don't clash with those used in the type and constructor declarations, we have

```
subElem : {idx : Nat} -> (0 p : IsVar name idx ws) ->
          SubVars zs ws -> Maybe (Var zs)
subElem p SubRefl = ?subElem_rhs_1
subElem p (DropCons x) = ?subElem_rhs_2
subElem p (KeepCons x) = ?subElem_rhs_3
```

and checking the type of `?subElem_rhs_2` yields  `x : SubVars zs ys`, correctly indicating the two lists as parameters in SubVars are not necessarily equal.

**Comment by gallais** [comment] 2020-12-04 11:07
This is a duplicate of #35.

**Closed by gallais** 2020-12-04 11:07 UTC
