### ISSUE TITLE
Relevance of package dependencies order

### ISSUE THREAD

**Issue by kasiaMarek** [idris-lang/Idris2#2575] opened 2022-07-07 12:57 UTC
# Steps to Reproduce
If you install tyre : https://github.com/kasiaMarek/TyRE and use this simple example of `tmp.idr` file:
```Idris
import Data.Regex

reg : TyRE ()
reg = r "a"
```
`idris2 -p tyre -p contrib tmp.idr` works fine
`idris2 -p contrib -p tyre tmp.idr` fails (it won't raise an error if you run the first one prior to running this, so make sure to delete `/build`)
# Expected Behavior
I would expect both of them behave the same and work fine. Otherwise, if it's expected for order to matter, I'd expect it to be consistent and fail regardless of cached build information.
I think the issue is that TyRE wants to run functions from `contrib` at type-level and fails to do so if the order of packages is not correct.
# Observed Behaviour
`idris2 -p contrib -p tyre tmp.idr` raises an error

**Comment by gallais** [comment] 2022-07-07 13:09
Is this a duplicate of #685?

**Comment by kasiaMarek** [comment] 2022-07-07 13:19
Yeah, I think it is...

**Closed** 2022-07-07 13:27 UTC
