### ISSUE TITLE
Cannot create a hole in with statement.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris2#732] opened 2020-10-05 15:13 UTC
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce

Take the following program:

```idris
module Bug

foo : Nat -> Nat
foo x = x

inc : Nat -> Nat
inc xs with (foo ?rhs)
  inc xs | with_path = ?inc
```
# Expected Behavior

I would expect that Idris would type check and produce a set of holes: `rhs` and `inc`.

# Observed Behavior

Idris complains with:

```
1/1: Building Bug (Bug.idr)
Error: While processing right hand side of inc. Bug.rhs is already defined.

Bug.idr:7:18--7:22
   |
 7 | inc xs with (foo ?rhs)
   |                  ^^^^

Error(s) building file Bug.idr
```

**Comment by gallais** [comment] 2020-10-05 19:15
Duplicate of #567

**Closed** 2020-10-05 19:16 UTC
Labels: admin: duplicate

**Comment by jfdm** [comment] 2020-10-06 19:31
fudge! thanks for spotting the duplicate. I thought I had searched the issues already. Alas I missed one.
