### ISSUE TITLE
Idris failed to recognize relative path

### ISSUE THREAD

**Issue by glyh** [idris-lang/Idris2#1515] opened 2021-06-07 10:03 UTC
# Steps to Reproduce
```
$ idris2 -p contrib ./src/Regex.idr
```

# Expected Behavior

Module loads and compiles.

# Observed Behavior
```
Welcome to Idris 2.  Enjoy yourself!
1/1: Building ..src.Regex (./src/Regex.idr)
Error: Module name Regex does not match file name "./src/Regex.idr"
```

**Comment by gallais** [comment] 2021-06-07 10:30
This is a duplicate of #1217

**Closed by gallais** 2021-06-07 10:30 UTC
