### ISSUE TITLE
Totality Checker False Negative

### ISSUE THREAD

**Issue by frankt716** [idris-lang/Idris2#2664] opened 2022-09-15 21:09 UTC
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
Both of the following instances passed the totality checker.

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/51205933/190509068-ae23a240-ede9-4e57-9e32-16923eccde4d.png">

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/51205933/190509123-da31d311-fef1-4b74-9db8-ae6a03f7d9c3.png">

# Expected Behavior
The totality checker should have rejected the code due to the recursive path `plus_comm (S k) m -> plus_comm (S k) m`

# Observed Behavior
Passed the totality checker.

**Comment by CodingCellist** [comment] 2022-09-16 08:38
Code for easy copy-pasting:
```idris
total
totalBug : (n, m : Nat) -> n + m === m + n
totalBug 0 0 = Refl
totalBug 0 (S k) = let eq = totalBug 0 k in rewrite sym eq in Refl
totalBug (S k) m = rewrite totalBug (S k) m in Refl
```

**Comment by gallais** [comment] 2022-09-16 10:34
I suspect that's a duplicate of #2448

**Closed by gallais** 2022-09-16 10:34 UTC
Labels: status: confirmed bug, safety: totality, language: rewrite
