### ISSUE TITLE
Implicits in Interface Functions cause Typecheck Error

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#67] opened 2020-05-20 12:51 UTC
<a href="https://github.com/fabianhjr"><img src="https://avatars0.githubusercontent.com/u/303897?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fabianhjr](https://github.com/fabianhjr)**
_Wednesday Apr 29, 2020 at 03:34 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/336_

----

# Steps to Reproduce

```
module Test

interface Foo a where
  bar : a -> {auto ok: ()} -> a 
```

# Expected Behavior

Typecheck (Like Idris1)

# Observed Behavior

```
1/1: Building Test (Test.idr)
Test.idr:4:3--5:1:While processing left hand side of bar at Test.idr:4:3--5:1:
ok is not a valid implicit argument in bar
```

Edit: maybe related to #8, however I couldn't change it to a constraint as a workaround since I was restricting the domain of a division to nonzero elements.

**Comment by edwinb** [comment] 2020-05-20 12:51
<a href="https://github.com/rgrover"><img src="https://avatars1.githubusercontent.com/u/112704?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rgrover](https://github.com/rgrover)**
_Wednesday Apr 29, 2020 at 03:39 GMT_

----

The following rewrite doesn't give a type error: 
```idris
module Foo

interface Foo a where
  bar : {auto ok: ()} -> a -> a
```

perhaps the implicit argument needs to be the first.

**Comment by edwinb** [comment] 2020-05-20 12:51
<a href="https://github.com/fabianhjr"><img src="https://avatars0.githubusercontent.com/u/303897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fabianhjr](https://github.com/fabianhjr)**
_Wednesday Apr 29, 2020 at 03:40 GMT_

----

@rgrover, the issue is that I was working on div/mod and wanted to remove the ring's zero:

```
div : (n, d: a) -> {auto ok: d `NEQ` Semiring.zero} -> a
```

(I did check the issue #8 with the constraint workaround suggestion)

**Comment by edwinb** [comment] 2020-05-20 12:51
<a href="https://github.com/rgrover"><img src="https://avatars1.githubusercontent.com/u/112704?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rgrover](https://github.com/rgrover)**
_Wednesday Apr 29, 2020 at 03:49 GMT_

----

Could the style in https://github.com/edwinb/Idris2/blob/master/libs/base/Data/Nat.idr#L191 work for you?

**Comment by edwinb** [comment] 2020-05-20 12:51
<a href="https://github.com/fabianhjr"><img src="https://avatars0.githubusercontent.com/u/303897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fabianhjr](https://github.com/fabianhjr)**
_Wednesday Apr 29, 2020 at 04:05 GMT_

----

Well, it would typecheck but so would any usages of div that didn't verify that they weren't dividing by zero. (Or ask for such a proof explicitly when it could attempt to derive it)

**Comment by edwinb** [comment] 2020-05-20 12:51
<a href="https://github.com/rgrover"><img src="https://avatars1.githubusercontent.com/u/112704?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rgrover](https://github.com/rgrover)**
_Wednesday Apr 29, 2020 at 04:14 GMT_

----

```idris
div : (n, d: a) -> Not (d = Semiring.zero) -> a
```

**Comment by mr-infty** [comment] 2020-09-12 16:24
@fabianhjr Wanting to be able to use implicit variables in interface methods, I tried to figure out what's going on. Here is what I found out.

The error message in question is triggered by `checkAppWith` in `src/TTImp/Elab/App.idr` by these lines of code:

    checkAppWith rig elabinfo nest env fc tm ty argdata [] impargs kr expty
        = case filter notInfer impargs of
               [] => checkAppWith rig elabinfo nest env fc tm ty argdata [] [] kr expty
               is => throw (InvalidImplicits fc env (map fst is) tm)
      where
        notInfer : (Maybe Name, RawImp) -> Bool
        notInfer (_, Implicit _ _) = False
        notInfer (n, IAs _ _ _ i) = notInfer (n, i)
        notInfer _ = True

In your example, `impargs` equals "[(Just ok, $ok)]", i.e. it contains one pair `(n, ty)` with `ty` of the form `IBindVar`. Thus `notInfer (n,ty)` evalutes to True.

It's not clear to me what the function `notInfer` is supposed to do, and therefore whether it's implemented incorrectly, or whether the value of `impargs` should be different.

**Comment by mr-infty** [comment] 2020-10-18 17:56
Additional note: The error is caused by the projection function implicitly created by the record to which the interface desugars. In particular it is not specific to interfaces or records but can easily be recreated as follows:

    foo : Void -> {auto ok: ()} -> Void
    foo = ?foo_hole

This triggers the same error message when being type-checked in Idris 2, whereas it type-checks just fine in Idris 1.

**Comment by mr-infty** [comment] 2020-11-06 18:54
After further research, it seems to me that the problem lies in Idris 2's way of treating pattern match definition. More precisely, as far as I understood the code, Idris 2 adds implicit variables to the lhs of pattern clauses.

This is effected in `TTImp.ProcessDef.checkLHS` by the following block of code (in `TTImp/Process.idr`)

    lhs <- if trans
              then pure lhs_bound
              else implicitsAs defs vars lhs_bound

resp. by

    setAs is (IVar loc n)
        = case !(lookupTyExact n (gamma defs)) of
               Nothing => pure $ IVar loc n
               Just ty => pure $ impAs loc
                                    !(findImps is !(nf defs [] ty)) (IVar loc n)

in `TTImp/TTImp.idr`.

In the example, `setAs` converts the `IVar` `foo` of the lhs of the above pattern clause into the `IImplicitApp` `foo [Just ok = $ok]`, which is ill-typed, as the implicit argument `ok` is applied out-of-order. In other words, Idris 2 seems to treat

    foo : Void -> {auto ok : ()} -> Void
    foo = ?foo_hole

as

    foo : Void -> {auto ok : ()} -> Void
    foo {ok} = ?foo_hole

In contrast, in Idris 1 (as in Agda), implicits arent't added automatically. Accordingly, the type of `foo_hole` is reported to be `Void -> () -> Void`.

**Comment by mr-infty** [comment] 2021-01-12 15:52
I've made a pull-request #918 that fixes this problem by changing the way in which the left hand side of a pattern matching declaration is elaborated. Implicits arguments now are no longer added beyond explicit arguments that haven't been given. This was made under the assumption that the behaviour of `checkAppWith` is correct and that the error lies in the elaboration (i.e. in `TTImp.TTImp.implicitsAs`).

**Closed** 2021-01-20 19:13 UTC

**Comment by fabianhjr** [comment] 2021-01-20 19:29
Thanks @mr-infty for working on this. <3

**Comment by mr-infty** [comment] 2021-01-20 21:55
> Thanks @mr-infty for working on this. <3

My pleasure. I'm glad too that this bug is ouf of the way now.
