### ISSUE TITLE
JavaScript backend: booleans are treated as ints

### ISSUE THREAD

**Issue by emccorson** [idris-lang/Idris2#2620] opened 2022-08-12 07:32 UTC
# Steps to Reproduce

Compile the following with the JavaScript codegen and run in the browser:

```idris
%foreign "browser:lambda: () => true"
prim__getBool : PrimIO Bool

getBool : IO Bool
getBool = primIO prim__getBool

showIt : Bool -> String
showIt False = "bad"
showIt True = "good"

main : IO ()
main = getBool >>= \b => putStrLn (showIt b)
```

# Expected Behavior

`good` will be logged in the browser console.

# Observed Behavior

`undefined` is logged in the browser console.

---

Idris is generating this function:

```idris
function Main_showIt($0) {
 switch($0) {
  case 0: return 'bad';
  case 1: return 'good';
 }
}
```

...but `$0` is a boolean so the switch statement doesn't match any case and `undefined` is returned.

I'm actually not sure if this is expected behaviour (since Bool is just a data type so each constructor should correspond to an integer), or whether Bool should be treated specially by the backend.

It does mean that writing JavaScript functions that return booleans gets ugly since instead of:

```javascript
() => true
```

you'd have to write:

```javascript
() => 1
```

**Comment by stefan-hoeck** [comment] 2022-08-12 07:34
This is expected behavior: `Bool` is not a primitive type in Idris and can therefore not be marshalled directly via the FFI.

**Comment by gallais** [comment] 2022-08-12 07:36
Duplicate of #946

**Closed by gallais** 2022-08-12 07:36 UTC
