### ISSUE TITLE
:doc hides referenced names of non-dependent function parameters

### ISSUE THREAD

**Issue by timsueberkrueb** [idris-lang/Idris2#2309] opened 2022-02-04 22:55 UTC
In general, names of function parameters of non-dependent functions should not be pretty-printed.
However, in the case where they are referenced in a doc string, they should be printed, otherwise it is unclear where these references to names in doc strings point to.

# Steps to Reproduce

Consider this interface definition:

```idr
import Data.Vect

interface Foo where
  ||| @n: the number
  foo : (n : Nat) -> Vect n Nat -> String
  ||| @n: the number  
  bar : (n : Nat) -> List Nat -> String
```

# Expected Behavior

Since the parameter `n` for `bar` is mentioned in the doc string, it should appear in the printed type signature:

```idr
:doc Foo

interface Main.Foo : Type
  Methods:
    foo : (n : Nat) -> Vect n Nat -> String
      @n: the number
    bar : (n : Nat) -> List Nat -> String
      @n: the number
```
# Observed Behavior

However, it does not:

```idr
:doc Foo

interface Main.Foo : Type
  Methods:
    foo : (n : Nat) -> Vect n Nat -> String
      @n: the number
    bar : Nat -> List Nat -> String
      @n: the number
```

**Comment by gallais** [comment] 2022-02-04 23:14
That's a duplicate of #1387

**Closed by gallais** 2022-02-04 23:14 UTC
