### ISSUE TITLE
The elaborator sometimes invents "fresh" names which are already in scope

### ISSUE THREAD

**Issue by bkomuves** [idris-lang/Idris2#2104] opened 2021-11-05 18:42 UTC
Consider the following program (with holes):
```
import Data.Fin

fun : {n : Nat} -> (k : Nat) -> Fin n -> Bool
fun k i = case i of
  FZ     => ?foo
  (FS _) => ?bar
```
Loading this in the REPL and executing `:t foo` results in
```
   k : Nat
   i : Fin (S k)
   n : Nat
------------------------------
foo : Bool
```
However the two `k`-s are different ones: The first one is the first argument of `fun`, while the second is the predecessor of `n` (which is inferred to be the successor of something, and this something is given the name `k`). This can be checked by renaming the argument to something different.

This is _really_ confusing, especially in a more complicated program.

I guess the compiler using `k` here has something to do with line `%name Nat k, j, i` in `Prelude.Types`.

In any case, it should never invent names which are already in scope. (I also think it is questionable to default do a completely different name instead of something related to `n`, but that's a separate issue...).

# Steps to Reproduce

Load the above snippet in the REPL, and execute `:t foo` (or `:t bar`)

# Expected Behavior

The output should be something like:
```
   k : Nat
   i : Fin (S n1)
   n : Nat
------------------------------
foo : Bool
```
with `n1` being a fresh name, not already in scope.

# Observed Behavior

The output is:
```
   k : Nat
   i : Fin (S k)
   n : Nat
------------------------------
foo : Bool
```

**Comment by gallais** [comment] 2021-11-05 19:03
This is a duplicate of #35

**Closed by gallais** 2021-11-05 19:03 UTC
