### ISSUE TITLE
Parsing of comment --}

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris2#711] opened 2020-09-30 09:58 UTC
# Steps to Reproduce

```
--}

i : Int
i = 100
```

The first line is not parsed as a comment in Idris 2.

# Expected Behavior

Idris 1 parses the file correctly.

# Observed Behavior

**Comment by gallais** [comment] 2020-09-30 10:21
If `--}` is considered a valid one-line comment then it cannot be a valid closing
token for a multiline comment if we want things to nest properly. This means that

```idris
{-----------------------------------
This is not a valid comment anymore
-----------------------------------}
```

I think the current parser is working as expected.

**Comment by MilanKral** [comment] 2020-09-30 11:46
I would then recommend to clarify this behaviour in Idris 2 documentation.

**Comment by gallais** [comment] 2021-02-22 12:12
This is a duplicate of #472

**Closed by gallais** 2021-02-22 12:12 UTC
Labels: documentation, good first issue, implem: parsing, status: expected behaviour
